### PR TITLE
completed simple rails auth and basic posting fuctionality

### PR DESCRIPTION
**Pull request by imhta**

### CODE REVIEW

**Comment by imhta** [comment]
sorry, we forgot and merged to develop branch.

> - I can create a post without a title or content, please address
I feel it is good to have validation and required field for title and content as a project

**Comment by mcrd25** [comment]
There required changes yo be made 😅.

Submit another review request after making changes and explain the
situation. 😊

**Comment by imhta** [comment]
> # Let's do this 💪
> Hi Team,
> 
> You have implemented MOST of the required changes. Thank you soo much for hearing me out! 🙏
> However, you have forgotten to address the helper method issue. Please address and submit another code review. Here's the link to the article again: http://codefol.io/posts/Where-Do-I-Put-My-Code/
> 
> **Congrats on successfully fixing your linter issues 🎊 😅**
> 
> Everything else looks fine!
> 
> _**Please makes changes and submit another review request. If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.**_
> 
> _Happy coding 😄,_
> **[--Maya](https://github.com/mcrd25)**
> [GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

**Comment by imhta** [comment]
> # Let's do this 💪
> Hi Team,
> 
> You have implemented MOST of the required changes. Thank you soo much for hearing me out! 🙏
> However, you have forgotten to address the helper method issue. Please address and submit another code review. Here's the link to the article again: http://codefol.io/posts/Where-Do-I-Put-My-Code/
> 
> **Congrats on successfully fixing your linter issues 🎊 😅**
> 
> Everything else looks fine!
> 
> _**Please makes changes and submit another review request. If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.**_
> 
> _Happy coding 😄,_
> **[--Maya](https://github.com/mcrd25)**
> [GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

I thought it was optional. Then for reference, I just looked into your repo for this project. Sorry, I believe session helper in your repo and ours are exactly the same. then what we have to change?.

**Comment by azdrenymeri** [comment]
## Hello @imhta :wave: 
You did a great job on this project. :1st_place_medal: 
### [OPTIONAL] 
* Files generated under `app/helpers/controller_helper.rb` are used to create helper methods for the views(templates) of that particular controller.
In other words when your views are getting bigger and maybe complex you can split your logic and create helper methods(on these helpers files) and then call them on your view.

* You have some methods defined (`current_user`,`logged_in?`,`store_location`)on your `app/helpers/sessions_helper.rb`and you are  calling them on your `posts_controller.rb` and `sessions_controller.rb` which is not a good practise.
* If you want a method to be available on all controllers then a good place to declare them is the `app/controllers/application_controller.rb`.
### You can go ahead and merge it.

**Pull request merged**
